name: snapnfix
description: "SNAPNFIX"

publish_to: 'none'


version: 1.0.3+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.0.9
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_screenutil: ^5.9.3
  smooth_page_indicator: ^1.2.1
  flutter_svg: ^2.0.17
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  flutter_bloc: ^9.1.0
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  pretty_dio_logger: ^1.4.0
  get_it: ^8.0.3
  firebase_core: ^3.12.1
  shared_preferences: ^2.5.2
  flutter_secure_storage: ^9.2.4
  go_router: ^14.8.1
  image_picker:
  dotted_border: ^2.1.0
  permission_handler: ^12.0.0+1
  geolocator: ^14.0.0
  connectivity_plus: ^6.1.3
  path_provider: ^2.1.5
  uuid: ^4.5.1
  equatable: ^2.0.7
  flutter_otp_text_field: ^1.5.1+1
  google_maps_flutter: ^2.12.1
  rxdart: ^0.28.0
  package_info_plus: ^8.3.0
  url_launcher: ^6.1.7
  cached_network_image: ^3.4.1
  animations: ^2.0.11
  device_info_plus: ^11.4.0
  dartz: ^0.10.1
  google_sign_in: ^6.3.0
  flutter_facebook_auth: ^7.1.2
  carousel_slider: ^5.0.0
  geocoding: ^3.0.0
  flutter_card_swiper: ^7.0.2
  injectable: ^2.5.0
  hive_flutter: ^1.1.0
  hydrated_bloc: ^10.0.0
  flutter_staggered_grid_view: ^0.7.0
  firebase_messaging: ^15.2.7
  flutter_local_notifications: ^19.2.1
  firebase_database: ^11.3.7
  device_preview : ^1.2.0

dev_dependencies:
  flutter_gen_runner: ^5.10.0
  injectable_generator: ^2.6.2
  build_runner: ^2.4.15
  hive_generator: ^2.0.1
  freezed: ^2.4.5
  json_serializable: ^6.9.0
  retrofit_generator: ^9.1.9
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/active/
flutter_gen:
  output: lib/l10n
  line_length: 80

