default_platform(:android)

platform :android do
  desc "Lane for android firebase app distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter pub get"
    sh "cd #{Dir.pwd}/../.. && flutter gen-l10n"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:769076416298:android:af06beb46470b8f8979853",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "abdelrhmanrmuhammed@gmail.com, abdelrahmanatef45@gmail.com, abdelrahmanadel203@gmail.com, leewenhoek22@gmail.com, roaa20102002@gmail.com",   
      release_notes: "Integration with Google Maps API",
    )
  end
end
